// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Bouduin.Lib.Holidays.Configurations</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>None</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Bouduin.Lib.Holidays.Configurations
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public partial class Configuration
    {

        private Holidays holidaysField;

        private List<Configuration> subConfigurationsField;

        private string hierarchyField;

        private string descriptionField;

        /// <summary>
        /// Configuration class constructor
        /// </summary>
        public Configuration()
        {
            this.subConfigurationsField = new List<Configuration>();
            this.holidaysField = new Holidays();
        }

        public Holidays Holidays
        {
            get
            {
                return this.holidaysField;
            }
            set
            {
                this.holidaysField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("SubConfigurations")]
        public List<Configuration> SubConfigurations
        {
            get
            {
                return this.subConfigurationsField;
            }
            set
            {
                this.subConfigurationsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hierarchy
        {
            get
            {
                return this.hierarchyField;
            }
            set
            {
                this.hierarchyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class Holidays
    {

        private List<Fixed> fixedField;

        private List<RelativeToFixed> relativeToFixedField;

        private List<RelativeToWeekdayInMonth> relativeToWeekdayInMonthField;

        private List<FixedWeekdayInMonth> fixedWeekdayField;

        private List<ChristianHoliday> christianHolidayField;

        private List<IslamicHoliday> islamicHolidayField;

        private List<FixedWeekdayBetweenFixed> fixedWeekdayBetweenFixedField;

        private List<FixedWeekdayRelativeToFixed> fixedWeekdayRelativeToFixedField;

        private List<HinduHoliday> hinduHolidayField;

        private List<HebrewHoliday> hebrewHolidayField;

        private List<EthiopianOrthodoxHoliday> ethiopianOrthodoxHolidayField;

        private List<RelativeToEasterSunday> relativeToEasterSundayField;

        /// <summary>
        /// Holidays class constructor
        /// </summary>
        public Holidays()
        {
            this.relativeToEasterSundayField = new List<RelativeToEasterSunday>();
            this.ethiopianOrthodoxHolidayField = new List<EthiopianOrthodoxHoliday>();
            this.hebrewHolidayField = new List<HebrewHoliday>();
            this.hinduHolidayField = new List<HinduHoliday>();
            this.fixedWeekdayRelativeToFixedField = new List<FixedWeekdayRelativeToFixed>();
            this.fixedWeekdayBetweenFixedField = new List<FixedWeekdayBetweenFixed>();
            this.islamicHolidayField = new List<IslamicHoliday>();
            this.christianHolidayField = new List<ChristianHoliday>();
            this.fixedWeekdayField = new List<FixedWeekdayInMonth>();
            this.relativeToWeekdayInMonthField = new List<RelativeToWeekdayInMonth>();
            this.relativeToFixedField = new List<RelativeToFixed>();
            this.fixedField = new List<Fixed>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Fixed")]
        public List<Fixed> Fixed
        {
            get
            {
                return this.fixedField;
            }
            set
            {
                this.fixedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("RelativeToFixed")]
        public List<RelativeToFixed> RelativeToFixed
        {
            get
            {
                return this.relativeToFixedField;
            }
            set
            {
                this.relativeToFixedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("RelativeToWeekdayInMonth")]
        public List<RelativeToWeekdayInMonth> RelativeToWeekdayInMonth
        {
            get
            {
                return this.relativeToWeekdayInMonthField;
            }
            set
            {
                this.relativeToWeekdayInMonthField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("FixedWeekday")]
        public List<FixedWeekdayInMonth> FixedWeekday
        {
            get
            {
                return this.fixedWeekdayField;
            }
            set
            {
                this.fixedWeekdayField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ChristianHoliday")]
        public List<ChristianHoliday> ChristianHoliday
        {
            get
            {
                return this.christianHolidayField;
            }
            set
            {
                this.christianHolidayField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("IslamicHoliday")]
        public List<IslamicHoliday> IslamicHoliday
        {
            get
            {
                return this.islamicHolidayField;
            }
            set
            {
                this.islamicHolidayField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("FixedWeekdayBetweenFixed")]
        public List<FixedWeekdayBetweenFixed> FixedWeekdayBetweenFixed
        {
            get
            {
                return this.fixedWeekdayBetweenFixedField;
            }
            set
            {
                this.fixedWeekdayBetweenFixedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("FixedWeekdayRelativeToFixed")]
        public List<FixedWeekdayRelativeToFixed> FixedWeekdayRelativeToFixed
        {
            get
            {
                return this.fixedWeekdayRelativeToFixedField;
            }
            set
            {
                this.fixedWeekdayRelativeToFixedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("HinduHoliday")]
        public List<HinduHoliday> HinduHoliday
        {
            get
            {
                return this.hinduHolidayField;
            }
            set
            {
                this.hinduHolidayField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("HebrewHoliday")]
        public List<HebrewHoliday> HebrewHoliday
        {
            get
            {
                return this.hebrewHolidayField;
            }
            set
            {
                this.hebrewHolidayField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("EthiopianOrthodoxHoliday")]
        public List<EthiopianOrthodoxHoliday> EthiopianOrthodoxHoliday
        {
            get
            {
                return this.ethiopianOrthodoxHolidayField;
            }
            set
            {
                this.ethiopianOrthodoxHolidayField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("RelativeToEasterSunday")]
        public List<RelativeToEasterSunday> RelativeToEasterSunday
        {
            get
            {
                return this.relativeToEasterSundayField;
            }
            set
            {
                this.relativeToEasterSundayField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class Fixed : MoveableHoliday
    {

        private Month monthField;

        private int dayField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Month month
        {
            get
            {
                return this.monthField;
            }
            set
            {
                this.monthField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum Month
    {

        /// <remarks/>
        JANUARY,

        /// <remarks/>
        FEBRUARY,

        /// <remarks/>
        MARCH,

        /// <remarks/>
        MAY,

        /// <remarks/>
        JUNE,

        /// <remarks/>
        JULY,

        /// <remarks/>
        AUGUST,

        /// <remarks/>
        SEPTEMBER,

        /// <remarks/>
        OCTOBER,

        /// <remarks/>
        NOVEMBER,

        /// <remarks/>
        DECEMBER,

        /// <remarks/>
        APRIL,
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChristianHoliday))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fixed))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public abstract partial class MoveableHoliday : Holiday
    {

        private List<MovingCondition> movingConditionField;

        /// <summary>
        /// MoveableHoliday class constructor
        /// </summary>
        public MoveableHoliday()
        {
            this.movingConditionField = new List<MovingCondition>();
        }

        [System.Xml.Serialization.XmlElementAttribute("MovingCondition")]
        public List<MovingCondition> MovingCondition
        {
            get
            {
                return this.movingConditionField;
            }
            set
            {
                this.movingConditionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class MovingCondition
    {

        private Substituted substituteField;

        private With withField;

        private Weekday weekdayField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Substituted substitute
        {
            get
            {
                return this.substituteField;
            }
            set
            {
                this.substituteField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public With with
        {
            get
            {
                return this.withField;
            }
            set
            {
                this.withField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Weekday weekday
        {
            get
            {
                return this.weekdayField;
            }
            set
            {
                this.weekdayField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum Substituted
    {

        /// <remarks/>
        ON_SATURDAY,

        /// <remarks/>
        ON_SUNDAY,

        /// <remarks/>
        ON_WEEKEND,

        /// <remarks/>
        ON_MONDAY,

        /// <remarks/>
        ON_TUESDAY,

        /// <remarks/>
        ON_WEDNESDAY,

        /// <remarks/>
        ON_THURSDAY,

        /// <remarks/>
        ON_FRIDAY,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum With
    {

        /// <remarks/>
        NEXT,

        /// <remarks/>
        PREVIOUS,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum Weekday
    {

        /// <remarks/>
        MONDAY,

        /// <remarks/>
        TUESDAY,

        /// <remarks/>
        WEDNESDAY,

        /// <remarks/>
        THURSDAY,

        /// <remarks/>
        FRIDAY,

        /// <remarks/>
        SATURDAY,

        /// <remarks/>
        SUNDAY,
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelativeToEasterSunday))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FixedWeekdayRelativeToFixed))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EthiopianOrthodoxHoliday))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HebrewHoliday))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HinduHoliday))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FixedWeekdayBetweenFixed))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IslamicHoliday))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelativeToWeekdayInMonth))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FixedWeekdayInMonth))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveableHoliday))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChristianHoliday))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fixed))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelativeToFixed))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public abstract partial class Holiday
    {

        private int validFromField;

        private int validToField;

        private HolidayCycleType everyField;

        private string descriptionPropertiesKeyField;

        private HolidayType localizedTypeField;

        public Holiday()
        {
            this.everyField = HolidayCycleType.EVERY_YEAR;
            this.localizedTypeField = HolidayType.OFFICIAL_HOLIDAY;
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int validFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int validTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(HolidayCycleType.EVERY_YEAR)]
        public HolidayCycleType every
        {
            get
            {
                return this.everyField;
            }
            set
            {
                this.everyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string descriptionPropertiesKey
        {
            get
            {
                return this.descriptionPropertiesKeyField;
            }
            set
            {
                this.descriptionPropertiesKeyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(HolidayType.OFFICIAL_HOLIDAY)]
        public HolidayType localizedType
        {
            get
            {
                return this.localizedTypeField;
            }
            set
            {
                this.localizedTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum HolidayCycleType
    {

        /// <remarks/>
        EVERY_YEAR,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2_YEARS")]
        Item2_YEARS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4_YEARS")]
        Item4_YEARS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5_YEARS")]
        Item5_YEARS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6_YEARS")]
        Item6_YEARS,

        /// <remarks/>
        ODD_YEARS,

        /// <remarks/>
        EVEN_YEARS,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum HolidayType
    {

        /// <remarks/>
        OFFICIAL_HOLIDAY,

        /// <remarks/>
        UNOFFICIAL_HOLIDAY,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class RelativeToEasterSunday : Holiday
    {

        private ChronologyType chronologyField;

        private int daysField;

        public ChronologyType chronology
        {
            get
            {
                return this.chronologyField;
            }
            set
            {
                this.chronologyField = value;
            }
        }

        public int days
        {
            get
            {
                return this.daysField;
            }
            set
            {
                this.daysField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum ChronologyType
    {

        /// <remarks/>
        JULIAN,

        /// <remarks/>
        GREGORIAN,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class FixedWeekdayRelativeToFixed : Holiday
    {

        private Fixed dayField;

        private Which whichField;

        private Weekday weekdayField;

        private When whenField;

        /// <summary>
        /// FixedWeekdayRelativeToFixed class constructor
        /// </summary>
        public FixedWeekdayRelativeToFixed()
        {
            this.dayField = new Fixed();
        }

        public Fixed day
        {
            get
            {
                return this.dayField;
            }
            set
            {
                this.dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Which which
        {
            get
            {
                return this.whichField;
            }
            set
            {
                this.whichField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Weekday weekday
        {
            get
            {
                return this.weekdayField;
            }
            set
            {
                this.weekdayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public When when
        {
            get
            {
                return this.whenField;
            }
            set
            {
                this.whenField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum Which
    {

        /// <remarks/>
        FIRST,

        /// <remarks/>
        SECOND,

        /// <remarks/>
        THIRD,

        /// <remarks/>
        LAST,

        /// <remarks/>
        FOURTH,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum When
    {

        /// <remarks/>
        BEFORE,

        /// <remarks/>
        AFTER,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class EthiopianOrthodoxHoliday : Holiday
    {

        private EthiopianOrthodoxHolidayType typeField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EthiopianOrthodoxHolidayType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum EthiopianOrthodoxHolidayType
    {

        /// <remarks/>
        TIMKAT,

        /// <remarks/>
        ENKUTATASH,

        /// <remarks/>
        MESKEL,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class HebrewHoliday : Holiday
    {

        private HebrewHolidayType typeField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public HebrewHolidayType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum HebrewHolidayType
    {

        /// <remarks/>
        ROSH_HASHANAH,

        /// <remarks/>
        ASERET_YEMEI_TESHUVA,

        /// <remarks/>
        YOM_KIPPUR,

        /// <remarks/>
        SUKKOT,

        /// <remarks/>
        SHEMINI_ATZERET,

        /// <remarks/>
        HANUKKAH,

        /// <remarks/>
        ASARAH_BETEVET,

        /// <remarks/>
        TU_BISHVAT,

        /// <remarks/>
        PURIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1_NISAN")]
        Item1_NISAN,

        /// <remarks/>
        PESACH,

        /// <remarks/>
        SEFIRAH,

        /// <remarks/>
        LAG_BAOMER,

        /// <remarks/>
        SHAVOUT,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17_TAMMUZ")]
        Item17_TAMMUZ,

        /// <remarks/>
        TISHA_BAV,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1_ELUL")]
        Item1_ELUL,

        /// <remarks/>
        ROSH_CODESH,

        /// <remarks/>
        SHABBAT,

        /// <remarks/>
        YOM_HASHOAH,

        /// <remarks/>
        YOM_HAZIKARON,

        /// <remarks/>
        YOM_HAATZAMAUT,

        /// <remarks/>
        YOM_YERUSHALAIM,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class HinduHoliday : Holiday
    {

        private HinduHolidayType typeField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public HinduHolidayType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum HinduHolidayType
    {

        /// <remarks/>
        HOLI,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class FixedWeekdayBetweenFixed : Holiday
    {

        private Fixed fromField;

        private Fixed toField;

        private Weekday weekdayField;

        /// <summary>
        /// FixedWeekdayBetweenFixed class constructor
        /// </summary>
        public FixedWeekdayBetweenFixed()
        {
            this.toField = new Fixed();
            this.fromField = new Fixed();
        }

        public Fixed from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        public Fixed to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Weekday weekday
        {
            get
            {
                return this.weekdayField;
            }
            set
            {
                this.weekdayField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class IslamicHoliday : Holiday
    {

        private IslamicHolidayType typeField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public IslamicHolidayType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum IslamicHolidayType
    {

        /// <remarks/>
        NEWYEAR,

        /// <remarks/>
        ASCHURA,

        /// <remarks/>
        MAWLID_AN_NABI,

        /// <remarks/>
        LAILAT_AL_MIRAJ,

        /// <remarks/>
        LAILAT_AL_BARAT,

        /// <remarks/>
        RAMADAN,

        /// <remarks/>
        LAILAT_AL_QADR,

        /// <remarks/>
        ID_AL_FITR,

        /// <remarks/>
        ID_UL_ADHA,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class RelativeToWeekdayInMonth : Holiday
    {

        private FixedWeekdayInMonth fixedWeekdayField;

        private Weekday weekdayField;

        private When whenField;

        /// <summary>
        /// RelativeToWeekdayInMonth class constructor
        /// </summary>
        public RelativeToWeekdayInMonth()
        {
            this.fixedWeekdayField = new FixedWeekdayInMonth();
        }

        public FixedWeekdayInMonth FixedWeekday
        {
            get
            {
                return this.fixedWeekdayField;
            }
            set
            {
                this.fixedWeekdayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Weekday weekday
        {
            get
            {
                return this.weekdayField;
            }
            set
            {
                this.weekdayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public When when
        {
            get
            {
                return this.whenField;
            }
            set
            {
                this.whenField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class FixedWeekdayInMonth : Holiday
    {

        private Which whichField;

        private Weekday weekdayField;

        private Month monthField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Which which
        {
            get
            {
                return this.whichField;
            }
            set
            {
                this.whichField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Weekday weekday
        {
            get
            {
                return this.weekdayField;
            }
            set
            {
                this.weekdayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Month month
        {
            get
            {
                return this.monthField;
            }
            set
            {
                this.monthField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class RelativeToFixed : Holiday
    {

        private object itemField;

        private When whenField;

        private Fixed dateField;

        /// <summary>
        /// RelativeToFixed class constructor
        /// </summary>
        public RelativeToFixed()
        {
            this.dateField = new Fixed();
        }

        [System.Xml.Serialization.XmlElementAttribute("Days", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("Weekday", typeof(Weekday))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        public When When
        {
            get
            {
                return this.whenField;
            }
            set
            {
                this.whenField = value;
            }
        }

        public Fixed Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = true)]
    public partial class ChristianHoliday : MoveableHoliday
    {

        private ChristianHolidayType typeField;

        private ChronologyType chronologyField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ChristianHolidayType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ChronologyType chronology
        {
            get
            {
                return this.chronologyField;
            }
            set
            {
                this.chronologyField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.example.org/Holiday")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.example.org/Holiday", IsNullable = false)]
    public enum ChristianHolidayType
    {

        /// <remarks/>
        GOOD_FRIDAY,

        /// <remarks/>
        EASTER_MONDAY,

        /// <remarks/>
        ASCENSION_DAY,

        /// <remarks/>
        WHIT_MONDAY,

        /// <remarks/>
        CORPUS_CHRISTI,

        /// <remarks/>
        MAUNDY_THURSDAY,

        /// <remarks/>
        ASH_WEDNESDAY,

        /// <remarks/>
        MARDI_GRAS,

        /// <remarks/>
        GENERAL_PRAYER_DAY,

        /// <remarks/>
        CLEAN_MONDAY,

        /// <remarks/>
        SHROVE_MONDAY,

        /// <remarks/>
        PENTECOST,

        /// <remarks/>
        CARNIVAL,

        /// <remarks/>
        EASTER_SATURDAY,

        /// <remarks/>
        EASTER_TUESDAY,

        /// <remarks/>
        SACRED_HEART,

        /// <remarks/>
        EASTER,

        /// <remarks/>
        PENTECOST_MONDAY,

        /// <remarks/>
        WHIT_SUNDAY,
    }
}
